### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by sachinvrg** [jennifert/JavaScript-Demos#1]
can you please check your demo on Moziall browser version - 40.0
https://www.jenntesolin.com/demos/single-map_bootstrap3.html 
I am still looking for an example of google map in bootstrap modal, I hope you will look at it.
Thank You.

**Comment by jennifert** [comment]
Thanks for the heads up. Will take a look and fix by tomorrow hopefully.

**Comment by jennifert** [comment]
Thanks. The problem was when I moved my site to come from SSL, I forgot to update the demo links. Everything should be working now.

Please let me know if your still seeing issues. If not, I will close this.

**Comment by sachinvrg** [comment]
Thanks Jennifer,

I'll check it soon, thank you for considering my issue.
