### ISSUE TITLE
Hacktoberfest - Bootstrap 5 - Singlemap

### ISSUE THREAD

**Issue by jennifert** [jennifert/JavaScript-Demos#13]
Create a single map point (google) using new bootstrap 5 framework.

**Comment by selamanse** [comment]
@jennifert I'd like to try this.

**Comment by jennifert** [comment]
> @jennifert I'd like to try this.

Very sorry, but I am already working on these and assigned to it.

**Comment by jennifert** [comment]
> @jennifert I'd like to try this.

There is a leaflet one if you want to try it. Or I just added new feature request templates. If there is something that would be great for beginners, use the temlate as an issue, and I willl mark as feature request and assign it to you.

Just follow the folder structure (e if its an express example, create folder called "express".
